vim.g.mapleader = " "
vim.keymap.set('n', '<leader>h'		, 	':nohlsearch<CR>')
vim.keymap.set('n', '<C-s>'    		, 	':split<CR>')
vim.keymap.set('n', '<M-Right>'		, 	':vertical resize +1<CR>')
vim.keymap.set('n', '<M-Left>' 		, 	':vertical resize -1<CR>')
vim.keymap.set('n', '<M-Up>'   		, 	':resize +1<CR>')
vim.keymap.set('n', '<M-Down>' 		, 	':resize -1<CR>')
vim.keymap.set('n', '<C-t>'    		, 	':split<CR>:terminal<CR>:startinsert<CR>')
vim.keymap.set('n', '<leader>e'		, 	':lua vim.diagnostic.open_float(0, {scope="line"})<CR>')
vim.keymap.set('n', '<C-PageUp>'	, 	':bnext<CR>')
vim.keymap.set('n', '<C-PageDown>'	, 	':bprevious<CR>')
vim.keymap.set('n', '<C-h>'	   		, 	'<C-W>h')
vim.keymap.set('n', '<C-j>'	   		, 	'<C-W>j')
vim.keymap.set('n', '<C-k>'	   		, 	'<C-W>k')
vim.keymap.set('n', '<C-l>'	   		, 	'<C-W>l')
vim.keymap.set('n', '<C-Left>' 		, 	'<C-W>h')
vim.keymap.set('n', '<C-Down>'   	, 	'<C-W>j')
vim.keymap.set('n', '<C-Up>'	   	, 	'<C-W>k')
vim.keymap.set('n', '<C-Right>'	   	, 	'<C-W>l')

